name: Concurrency
on: [workflow_dispatch]

jobs:
  job1:
    concurrency: g1
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - run: echo "Hello World! $(date)"

  job2:
    concurrency: g1
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - run: echo "Hello World! $(date)"

  job3:
    concurrency: 
      group: g2
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - run: echo "Hello World! $(date)"
  
  job4:
    concurrency: 
      group: g2
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - run: echo "Hello World! $(date)"
  


