name: GitHub Actions Demo
on: 
  push:
    branches:    
      - main
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches:    
      - main
  schedule:
    - cron : '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Output event name
      run: echo ${{ github.event_name }}

    - name: Output branch name
      run: echo ${{ github.ref }}
    
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: List files
      run: ls -R
      
